apiVersion: v1
kind: Service
metadata:
  name: product-management
spec:
  type: LoadBalancer
  selector:
    app: product-management
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000